In [1]:
import os
import pandas as pd
import wandb
import torch
import logging
from datetime import datetime
from huggingface_hub import login

from model import initialize_model, setup_peft
from data_utils import prepare_data
from trainer import train_model
from debug_utils import debug_misclassifications
from modules.utils import compute_metrics
from modules.utils import debug_misclassifications, setup_logging

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


In [2]:
def train_single_dataset(df, model_name, output_dir, current_date, dataset_name):
    """
    Train model on a single dataset
    
    Args:
        df: DataFrame containing the dataset
        model_name: Name of the model to use
        output_dir: Directory to save outputs
        current_date: Current date string for naming
        dataset_name: Name of the dataset for logging
    
    Returns:
        tuple: (results, model, tokenizer, label_mapping)
    """
    # Create dataset-specific output directory
    dataset_output_dir = os.path.join(output_dir, f"{dataset_name}_{current_date}")
    os.makedirs(dataset_output_dir, exist_ok=True)
    
    print(f"\nTraining on {dataset_name} dataset...")
    
    # Initialize wandb run for this dataset
    wandb.init(project="llama-classification", 
               name=f"llama-classification-{dataset_name}-{current_date}",
               reinit=True)
    
    # Prepare data
    train_dataset, val_dataset, tokenizer, label_mapping, num_labels = prepare_data(
        df, model_name, dataset_output_dir
    )

    # Initialize and setup model
    print("\nInitializing model...")
    model = initialize_model(model_name, num_labels)
    model = setup_peft(model)

    # Train model
    trainer = train_model(model, train_dataset, val_dataset, dataset_output_dir, current_date, dataset_name)

    # Evaluate model
    print("\nEvaluating model...")
    results = trainer.evaluate()
    
    print(f"\nEvaluation results for {dataset_name} dataset:")
    for metric, value in results.items():
        if isinstance(value, float):
            print(f"{metric}: {value:.4f}")
        else:
            print(f"{metric}: {value}")

    # Save model and tokenizer
    print(f"\nSaving {dataset_name} model...")
    trainer.save_model(dataset_output_dir)
    tokenizer.save_pretrained(dataset_output_dir)

    # Debug misclassifications
    misclass_df = debug_misclassifications(df, model, tokenizer, label_mapping)
    
    # End wandb run
    wandb.finish()
    
    return results, model, tokenizer, label_mapping


In [3]:
# Cell 1: Common Setup Code
def setup_training():
    try:
        # Login to Hugging Face
        login('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')

        # Check CUDA availability
        print(f"CUDA Available: {torch.cuda.is_available()}")
        if torch.cuda.is_available():
            print(f"GPU Device: {torch.cuda.get_device_name(0)}")
            print(f"GPU Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")

        # Set paths
        def find_repo_root():
            current = os.getcwd()
            while current != os.path.dirname(current):
                if os.path.exists(os.path.join(current, '.git')):
                    return current
                current = os.path.dirname(current)
            raise Exception("No .git directory found - repository root could not be determined")

        # Set paths using repository root
        repo_root = find_repo_root()
        code_path = os.path.join(repo_root, "code")
        current_date = datetime.now().strftime("%Y%m%d")
        output_dir = os.path.join(code_path, "models", f"llama_{current_date}")
        os.makedirs(output_dir, exist_ok=True)

        # Load data from code directory
        print("\nLoading datasets...")
        print(f"Repository root: {repo_root}")
        print(f"Looking for data files in: {code_path}")
        input_file_full = os.path.join(code_path, "df_normalized.csv")
        input_file_ua = os.path.join(code_path, "df_normalized_ua.csv")
        input_file_cc = os.path.join(code_path, "df_normalized_cc.csv")

        df_normalized = pd.read_csv(input_file_full)
        df_normalized_ua = pd.read_csv(input_file_ua)
        df_normalized_cc = pd.read_csv(input_file_cc)

        # Model configuration
        model_name = "openlm-research/open_llama_7b"
        
        return {
            'output_dir': output_dir,
            'current_date': current_date,
            'model_name': model_name,
            'df_normalized': df_normalized,
            'df_normalized_ua': df_normalized_ua,
            'df_normalized_cc': df_normalized_cc
        }

    except Exception as e:
        print(f"Error in setup: {str(e)}")
        import traceback
        traceback.print_exc()
        wandb.finish()
        raise

# Cell 2: Train UA Dataset
def train_ua():
    try:
        # Get setup configuration
        config = setup_training()
        
        print("\nStarting UA dataset training...")
        ua_results, ua_model, ua_tokenizer, ua_label_mapping = train_single_dataset(
            config['df_normalized_ua'], 
            config['model_name'], 
            config['output_dir'], 
            config['current_date'], 
            "ua"
        )
        
        return ua_results, ua_model, ua_tokenizer, ua_label_mapping
        
    except Exception as e:
        print(f"Error in UA training: {str(e)}")
        import traceback
        traceback.print_exc()
        wandb.finish()
        raise

# Cell 3: Train CC Dataset
def train_cc():
    try:
        # Get setup configuration
        config = setup_training()
        
        print("\nStarting CC dataset training...")
        cc_results, cc_model, cc_tokenizer, cc_label_mapping = train_single_dataset(
            config['df_normalized_cc'], 
            config['model_name'], 
            config['output_dir'], 
            config['current_date'], 
            "cc"
        )
        
        return cc_results, cc_model, cc_tokenizer, cc_label_mapping
        
    except Exception as e:
        print(f"Error in CC training: {str(e)}")
        import traceback
        traceback.print_exc()
        wandb.finish()
        raise

# Cell 4: Train Full Dataset
def train_full():
    try:
        # Get setup configuration
        config = setup_training()
        
        print("\nStarting full dataset training...")
        results, model, tokenizer, label_mapping = train_single_dataset(
            config['df_normalized'], 
            config['model_name'], 
            config['output_dir'], 
            config['current_date'], 
            "full"
        )
        
        return results, model, tokenizer, label_mapping
        
    except Exception as e:
        print(f"Error in full dataset training: {str(e)}")
        import traceback
        traceback.print_exc()
        wandb.finish()
        raise

In [4]:

config = setup_training()
# Train UA dataset
#ua_results, ua_model, ua_tokenizer, ua_label_mapping = train_ua()

CUDA Available: True
GPU Device: NVIDIA L40S
GPU Memory: 47.81 GB

Loading datasets...
Repository root: /teamspace/studios/this_studio/nlp_Backpropagandists_2024
Looking for data files in: /teamspace/studios/this_studio/nlp_Backpropagandists_2024/code


In [8]:
cc_results, cc_model, cc_tokenizer, cc_label_mapping = train_cc()

CUDA Available: True
GPU Device: NVIDIA L40S
GPU Memory: 47.81 GB

Loading datasets...
Repository root: /teamspace/studios/this_studio/nlp_Backpropagandists_2024
Looking for data files in: /teamspace/studios/this_studio/nlp_Backpropagandists_2024/code

Starting CC dataset training...

Training on cc dataset...



Creating narrative mapping...
Number of unique narratives: 11

Sample narrative mappings:
0: Amplifying Climate Fears
1: Climate change is beneficial
2: Controversy about green technologies
3: Criticism of climate movement
4: Criticism of climate policies

Training set size: 415
Validation set size: 104

Initializing tokenizer...

Tokenizing texts...

Initializing model...


2025-01-21 13:33:51,645 - INFO - We will use 90% of the memory on device 0 for storing the model, and 10% for the buffer to avoid OOM. You can set `max_memory` in to a higher value to use more memory (at your own risk).


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at openlm-research/open_llama_7b and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


trainable params: 16,822,272 || all params: 6,624,210,944 || trainable%: 0.2540

Starting classification head pre-training...


/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/utils/checkpoint.py:460: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(



Metrics for Class 0:
Confusion Matrix:
[[40 24]
 [ 3 37]]
Precision: 0.6066
Recall: 0.9250
F1 Score: 0.7327

Metrics for Class 1:
Confusion Matrix:
[[103   0]
 [  1   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 3:
Confusion Matrix:
[[94  2]
 [ 6  2]]
Precision: 0.5000
Recall: 0.2500
F1 Score: 0.3333

Metrics for Class 4:
Confusion Matrix:
[[98  2]
 [ 4  0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 5:
Confusion Matrix:
[[82 10]
 [10  2]]
Precision: 0.1667
Recall: 0.1667
F1 Score: 0.1667

Metrics for Class 6:
Confusion Matrix:
[[95  2]
 [ 7  0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 7:
Confusion Matrix:
[[103   0]
 [  1   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 8:
Confusion Matrix:
[[96  0]
 [ 8  0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 9:
Confusion Matrix:
[[69 13]
 [12 10]]
Precision: 0.4348
Recall: 0.4545
F1 Score: 0.4444

Metrics fo

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/z


Unfreezing LoRA adapters for full training...

Starting full model fine-tuning...


/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(



Metrics for Class 0:
Confusion Matrix:
[[40 24]
 [ 1 39]]
Precision: 0.6190
Recall: 0.9750
F1 Score: 0.7573

Metrics for Class 1:
Confusion Matrix:
[[103   0]
 [  1   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 3:
Confusion Matrix:
[[95  1]
 [ 7  1]]
Precision: 0.5000
Recall: 0.1250
F1 Score: 0.2000

Metrics for Class 4:
Confusion Matrix:
[[99  1]
 [ 4  0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 5:
Confusion Matrix:
[[90  2]
 [ 9  3]]
Precision: 0.6000
Recall: 0.2500
F1 Score: 0.3529

Metrics for Class 6:
Confusion Matrix:
[[96  1]
 [ 7  0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 7:
Confusion Matrix:
[[103   0]
 [  1   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 8:
Confusion Matrix:
[[96  0]
 [ 8  0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 9:
Confusion Matrix:
[[64 18]
 [ 8 14]]
Precision: 0.4375
Recall: 0.6364
F1 Score: 0.5185

Metrics fo

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/z


Metrics for Class 0:
Confusion Matrix:
[[50 14]
 [ 5 35]]
Precision: 0.7143
Recall: 0.8750
F1 Score: 0.7865

Metrics for Class 1:
Confusion Matrix:
[[103   0]
 [  1   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 3:
Confusion Matrix:
[[94  2]
 [ 5  3]]
Precision: 0.6000
Recall: 0.3750
F1 Score: 0.4615

Metrics for Class 4:
Confusion Matrix:
[[93  7]
 [ 2  2]]
Precision: 0.2222
Recall: 0.5000
F1 Score: 0.3077

Metrics for Class 5:
Confusion Matrix:
[[85  7]
 [ 9  3]]
Precision: 0.3000
Recall: 0.2500
F1 Score: 0.2727

Metrics for Class 6:
Confusion Matrix:
[[95  2]
 [ 7  0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 7:
Confusion Matrix:
[[103   0]
 [  1   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 8:
Confusion Matrix:
[[93  3]
 [ 7  1]]
Precision: 0.2500
Recall: 0.1250
F1 Score: 0.1667

Metrics for Class 9:
Confusion Matrix:
[[72 10]
 [ 9 13]]
Precision: 0.5652
Recall: 0.5909
F1 Score: 0.5778

Metrics fo

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/z


Metrics for Class 0:
Confusion Matrix:
[[51 13]
 [ 3 37]]
Precision: 0.7400
Recall: 0.9250
F1 Score: 0.8222

Metrics for Class 1:
Confusion Matrix:
[[103   0]
 [  1   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 3:
Confusion Matrix:
[[93  3]
 [ 3  5]]
Precision: 0.6250
Recall: 0.6250
F1 Score: 0.6250

Metrics for Class 4:
Confusion Matrix:
[[98  2]
 [ 3  1]]
Precision: 0.3333
Recall: 0.2500
F1 Score: 0.2857

Metrics for Class 5:
Confusion Matrix:
[[83  9]
 [ 6  6]]
Precision: 0.4000
Recall: 0.5000
F1 Score: 0.4444

Metrics for Class 6:
Confusion Matrix:
[[95  2]
 [ 7  0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 7:
Confusion Matrix:
[[103   0]
 [  1   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 8:
Confusion Matrix:
[[96  0]
 [ 7  1]]
Precision: 1.0000
Recall: 0.1250
F1 Score: 0.2222

Metrics for Class 9:
Confusion Matrix:
[[75  7]
 [ 7 15]]
Precision: 0.6818
Recall: 0.6818
F1 Score: 0.6818

Metrics fo

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/z


Evaluating model...



Metrics for Class 0:
Confusion Matrix:
[[50 14]
 [ 5 35]]
Precision: 0.7143
Recall: 0.8750
F1 Score: 0.7865

Metrics for Class 1:
Confusion Matrix:
[[103   0]
 [  1   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 3:
Confusion Matrix:
[[94  2]
 [ 5  3]]
Precision: 0.6000
Recall: 0.3750
F1 Score: 0.4615

Metrics for Class 4:
Confusion Matrix:
[[93  7]
 [ 2  2]]
Precision: 0.2222
Recall: 0.5000
F1 Score: 0.3077

Metrics for Class 5:
Confusion Matrix:
[[85  7]
 [ 9  3]]
Precision: 0.3000
Recall: 0.2500
F1 Score: 0.2727

Metrics for Class 6:
Confusion Matrix:
[[95  2]
 [ 7  0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 7:
Confusion Matrix:
[[103   0]
 [  1   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 8:
Confusion Matrix:
[[93  3]
 [ 7  1]]
Precision: 0.2500
Recall: 0.1250
F1 Score: 0.1667

Metrics for Class 9:
Confusion Matrix:
[[72 10]
 [ 9 13]]
Precision: 0.5652
Recall: 0.5909
F1 Score: 0.5778

Metrics fo

/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/z

Error in CC training: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper_CUDA__index_select)


Traceback (most recent call last):
  File "/tmp/ipykernel_1941/2645010921.py", line 91, in train_cc
    cc_results, cc_model, cc_tokenizer, cc_label_mapping = train_single_dataset(
  File "/tmp/ipykernel_1941/2084970581.py", line 56, in train_single_dataset
    misclass_df = debug_misclassifications(df, model, tokenizer, label_mapping)
  File "/teamspace/studios/this_studio/nlp_Backpropagandists_2024/code/modules/utils.py", line 126, in debug_misclassifications
    outputs = model(input_ids, attention_mask=attention_mask)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/peft/peft_model.py", line 1521, in forward
   

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper_CUDA__index_select)

In [5]:
# Train full dataset
results, model, tokenizer, label_mapping = train_full()

CUDA Available: True
GPU Device: NVIDIA L40S
GPU Memory: 47.81 GB

Loading datasets...
Repository root: /teamspace/studios/this_studio/nlp_Backpropagandists_2024
Looking for data files in: /teamspace/studios/this_studio/nlp_Backpropagandists_2024/code

Starting full dataset training...

Training on full dataset...


wandb: Currently logged in as: jonaskruse (backpropagandists). Use `wandb login --relogin` to force relogin
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.


You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565 - if you loaded a llama tokenizer from a GGUF file you can ignore this message



Creating narrative mapping...
Number of unique narratives: 21

Sample narrative mappings:
0: Amplifying Climate Fears
1: Amplifying war-related fears
2: Blaming the war on others rather than the invader
3: Climate change is beneficial
4: Controversy about green technologies

Training set size: 1355
Validation set size: 339

Initializing tokenizer...

Tokenizing texts...

Initializing model...


2025-01-21 13:59:01,940 - INFO - We will use 90% of the memory on device 0 for storing the model, and 10% for the buffer to avoid OOM. You can set `max_memory` in to a higher value to use more memory (at your own risk).


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at openlm-research/open_llama_7b and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


trainable params: 16,863,232 || all params: 6,624,292,864 || trainable%: 0.2546

Starting classification head pre-training...


`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/utils/checkpoint.py:460: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(



Metrics for Class 0:
Confusion Matrix:
[[266  37]
 [ 14  22]]
Precision: 0.3729
Recall: 0.6111
F1 Score: 0.4632

Metrics for Class 1:
Confusion Matrix:
[[307   9]
 [ 22   1]]
Precision: 0.1000
Recall: 0.0435
F1 Score: 0.0606

Metrics for Class 2:
Confusion Matrix:
[[312  10]
 [ 17   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 4:
Confusion Matrix:
[[338   0]
 [  1   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 5:
Confusion Matrix:
[[334   1]
 [  4   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 6:
Confusion Matrix:
[[327   9]
 [  3   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 7:
Confusion Matrix:
[[308  10]
 [ 20   1]]
Precision: 0.0909
Recall: 0.0476
F1 Score: 0.0625

Metrics for Class 8:
Confusion Matrix:
[[226  63]
 [ 27  23]]
Precision: 0.2674
Recall: 0.4600
F1 Score: 0.3382

Metrics for Class 9:
Confusion Matrix:
[[288  15]
 [ 36   0]]
Precision: 0.0000
Recall: 0.0000


/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/z


Unfreezing LoRA adapters for full training...

Starting full model fine-tuning...


/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(



Metrics for Class 0:
Confusion Matrix:
[[281  22]
 [  6  30]]
Precision: 0.5769
Recall: 0.8333
F1 Score: 0.6818

Metrics for Class 1:
Confusion Matrix:
[[287  29]
 [ 15   8]]
Precision: 0.2162
Recall: 0.3478
F1 Score: 0.2667

Metrics for Class 2:
Confusion Matrix:
[[318   4]
 [ 17   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 4:
Confusion Matrix:
[[338   0]
 [  1   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 5:
Confusion Matrix:
[[324  11]
 [  4   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 6:
Confusion Matrix:
[[336   0]
 [  3   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 7:
Confusion Matrix:
[[315   3]
 [ 19   2]]
Precision: 0.4000
Recall: 0.0952
F1 Score: 0.1538

Metrics for Class 8:
Confusion Matrix:
[[224  65]
 [ 24  26]]
Precision: 0.2857
Recall: 0.5200
F1 Score: 0.3688

Metrics for Class 9:
Confusion Matrix:
[[291  12]
 [ 32   4]]
Precision: 0.2500
Recall: 0.1111


/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/z


Metrics for Class 0:
Confusion Matrix:
[[286  17]
 [  7  29]]
Precision: 0.6304
Recall: 0.8056
F1 Score: 0.7073

Metrics for Class 1:
Confusion Matrix:
[[303  13]
 [ 19   4]]
Precision: 0.2353
Recall: 0.1739
F1 Score: 0.2000

Metrics for Class 2:
Confusion Matrix:
[[315   7]
 [ 16   1]]
Precision: 0.1250
Recall: 0.0588
F1 Score: 0.0800

Metrics for Class 4:
Confusion Matrix:
[[338   0]
 [  1   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 5:
Confusion Matrix:
[[331   4]
 [  4   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 6:
Confusion Matrix:
[[331   5]
 [  3   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 7:
Confusion Matrix:
[[311   7]
 [ 14   7]]
Precision: 0.5000
Recall: 0.3333
F1 Score: 0.4000

Metrics for Class 8:
Confusion Matrix:
[[231  58]
 [ 25  25]]
Precision: 0.3012
Recall: 0.5000
F1 Score: 0.3759

Metrics for Class 9:
Confusion Matrix:
[[285  18]
 [ 29   7]]
Precision: 0.2800
Recall: 0.1944


/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



Metrics for Class 0:
Confusion Matrix:
[[291  12]
 [  6  30]]
Precision: 0.7143
Recall: 0.8333
F1 Score: 0.7692

Metrics for Class 1:
Confusion Matrix:
[[298  18]
 [ 18   5]]
Precision: 0.2174
Recall: 0.2174
F1 Score: 0.2174

Metrics for Class 2:
Confusion Matrix:
[[313   9]
 [ 16   1]]
Precision: 0.1000
Recall: 0.0588
F1 Score: 0.0741

Metrics for Class 4:
Confusion Matrix:
[[338   0]
 [  1   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 5:
Confusion Matrix:
[[332   3]
 [  4   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 6:
Confusion Matrix:
[[330   6]
 [  3   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 7:
Confusion Matrix:
[[313   5]
 [ 19   2]]
Precision: 0.2857
Recall: 0.0952
F1 Score: 0.1429

Metrics for Class 8:
Confusion Matrix:
[[256  33]
 [ 33  17]]
Precision: 0.3400
Recall: 0.3400
F1 Score: 0.3400

Metrics for Class 9:
Confusion Matrix:
[[260  43]
 [ 26  10]]
Precision: 0.1887
Recall: 0.2778


/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/z


Evaluating model...



Metrics for Class 0:
Confusion Matrix:
[[281  22]
 [  6  30]]
Precision: 0.5769
Recall: 0.8333
F1 Score: 0.6818

Metrics for Class 1:
Confusion Matrix:
[[287  29]
 [ 15   8]]
Precision: 0.2162
Recall: 0.3478
F1 Score: 0.2667

Metrics for Class 2:
Confusion Matrix:
[[318   4]
 [ 17   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 4:
Confusion Matrix:
[[338   0]
 [  1   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 5:
Confusion Matrix:
[[324  11]
 [  4   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 6:
Confusion Matrix:
[[336   0]
 [  3   0]]
Precision: 0.0000
Recall: 0.0000
F1 Score: 0.0000

Metrics for Class 7:
Confusion Matrix:
[[315   3]
 [ 19   2]]
Precision: 0.4000
Recall: 0.0952
F1 Score: 0.1538

Metrics for Class 8:
Confusion Matrix:
[[224  65]
 [ 24  26]]
Precision: 0.2857
Recall: 0.5200
F1 Score: 0.3688

Metrics for Class 9:
Confusion Matrix:
[[291  12]
 [ 32   4]]
Precision: 0.2500
Recall: 0.1111


/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/z

Error in full dataset training: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper_CUDA__index_select)


Traceback (most recent call last):
  File "/tmp/ipykernel_82240/2645010921.py", line 115, in train_full
    results, model, tokenizer, label_mapping = train_single_dataset(
  File "/tmp/ipykernel_82240/2084970581.py", line 56, in train_single_dataset
    misclass_df = debug_misclassifications(df, model, tokenizer, label_mapping)
  File "/teamspace/studios/this_studio/nlp_Backpropagandists_2024/code/modules/utils.py", line 126, in debug_misclassifications
    outputs = model(input_ids, attention_mask=attention_mask)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/peft/peft_model.py", line 1521, in forward
    return

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper_CUDA__index_select)